### ISSUE TITLE
Extract trace_forwarder into a separate Lambda layer (and maybe a Git repo)

### ISSUE THREAD

**Issue by KIVagant** [DataDog/datadog-serverless-functions#306]
**Describe what happened:**

Following https://github.com/DataDog/datadog-serverless-functions/issues/264

Some teams need more than just to install [the `logs_monitoring` function](https://github.com/DataDog/datadog-serverless-functions/tree/master/aws/logs_monitoring) to AWS. In our case we should make significant changes to the function code to separate some logs from each other, filter out logs we don't need, load the API key from a secret store (instead of adding it into env vars as plain text). All of this require us to deploy the function using our own SAM templates and CI. It would be okay if it was only about templates and code refactoring. The biggest issue we got is that `trace_forwarder` requires a Shared Library file (`trace-intake.so`) to be compiled and uploaded together with the function code. From what I can consider, `trace_forwarder` is a self-sufficient part of this stack and potentially could be extracted into a separate layer. Also I don't see many use-cases where one would need to update the package code.

Our SAM template has a part that looks like this now:

```yaml

CloudwatchDatadogLogsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: logs_monitoring/
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      Tracing: Active
      Layers:
      # https://github.com/DataDog/datadog-lambda-layer-python/releases
      - !Sub 'arn:aws:lambda:${AWS::Region}:464622532012:layer:Datadog-${DatadogPythonLayerVersion}'
      - !Ref CloudwatchDatadogLogsFunctionLibs
      Environment:
```

It would be nice to inject the `trace_forwarder` using the same approach instead of compiling and uploading 20MB after every code change in `logs_monitoring`.
