### ISSUE TITLE
[Request] Forwarder lambda compatibility with AWS StackSets

### ISSUE THREAD

**Issue by ctmlr** [DataDog/datadog-serverless-functions#423]
**Describe what happened:**

I need to deploy the forwarded lambda in multiple regions in order to collect logs from my Lambda@Edge functions. I tried to do this with a stack set however the `AWS::Serverless-2016-10-31` transform used in the template is incompatible with the stack set feature and I get an error: `Templates with transforms are not supported with StackSets`

**Steps to reproduce the issue:**

Cloudformation example:

```
Resources:
  LogForwarderStackSet:
    Type: AWS::CloudFormation::StackSet
    Properties:
      Description: Deploy datadog forwarder lambda to multiple regions
      PermissionModel: SELF_MANAGED
      StackInstancesGroup:
        - DeploymentTargets:
            Accounts:
              - !Ref "AWS::AccountId"
          Regions:
            - us-east-1
            - sa-east-1
      StackSetName: logforwarder-stackset
      Parameters:
        - ParameterKey: DdApiKey
          ParameterValue: 'this_value_is_not_used'
        - ParameterKey: DdApiKeySecretArn
          ParameterValue: 'xxx'
      TemplateURL: https://datadog-cloudformation-template.s3.amazonaws.com/aws/forwarder/latest.yaml
```
