### ISSUE TITLE
Enforce TLS 1.2 on ForwarderBucketPolicy

### ISSUE THREAD

**Issue by k-drumz** [DataDog/datadog-serverless-functions#603]
**Describe what you expected:**
Can you add a parameter or option to enforce TLS v1.2 on the s3 `ForwarderBucketPolicy`?

Template reference:
https://github.com/DataDog/datadog-serverless-functions/blob/master/aws/logs_monitoring/template.yaml#L798-L815

Proposed policy:
```
ForwarderBucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref ForwarderBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowSSLRequestsOnly
            Action:
              - s3:*
            Effect: Deny
            Resource:
              - !Sub "${ForwarderBucket.Arn}"
              - !Sub "${ForwarderBucket.Arn}/*"
            Condition:
              Bool:
                "aws:SecureTransport": "false"
              NumericLessThan:
                "s3:TlsVersion": "1.2"
            Principal: "*"
```

Thank you!
