### ISSUE TITLE
Clarification request on memory/timeout for 'aws/logs_monitoring/lambda_function.py'

### ISSUE THREAD

**Issue by jalessio** [DataDog/datadog-serverless-functions#78]
I find three separate values for the recommended memory/timeout function for the AWS logs collection Lambda function. 

* Recommended function timeout ranges from 10 seconds to 120 seconds
* Recommended memory ranges from 128 to "the highest possible value".

Can you clarify which of these is preferred? Obviously, "more memory and longer timeout" is _safer_ but I'm curious if you can provide any guidance on memory usage as it relates to log volume. I'd prefer not to allocate the Lambda function a lot of memory that will never be used.

## README in Github project

https://github.com/DataDog/datadog-serverless-functions/tree/00e49919a1e1c453db5bb157f813d4b549be5f1e/aws/logs_monitoring

> Set the memory to the highest possible value.
> Set also the timeout limit. We recommends 120 seconds to deal with big files.

## Default values in `log-sam-template.yaml`

https://github.com/DataDog/datadog-serverless-functions/blob/00e49919a1e1c453db5bb157f813d4b549be5f1e/aws/logs_monitoring/log-sam-template.yaml

These values are considerably lower than what is recommended in the `README.md`

```
Resources:
  loglambdaddfunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: Pushes logs from S3 and CloudWatch Logs to Datadog.
      Handler: lambda_function.lambda_handler
      MemorySize: 128
      Runtime: python2.7
      Timeout: 10
```

### Datadog documentation

https://docs.datadoghq.com/integrations/amazon_web_services/?tab=allpermissions#provide-the-code-and-configure-the-lambda

<img width="675" alt="screen shot 2019-01-12 at 12 00 31 pm" src="https://user-images.githubusercontent.com/178680/51077931-2da67300-1662-11e9-85c2-983345a4560f.png">

Thanks!
